skonczone_1_zadanie
kamamenszu/jak-to-zrobic-w-js pull request #1
Opened 2018-12-30 12:06 UTC by kamamenszu

2018-12-30 19:27 UTC, jacekokrojek commented on htmlReport.html
> +<!DOCTYPE html><html><head lang=en><meta charset=UTF-8><title></title><style>body{font-family:"open_sans",sans-serif}.suite{width:100%;overflow:auto}.suite .stats{margin:0;width:90%;padding:0}.suite
Hej Kamilo, odkomentowałaś reportery i pliki jakie one generują dodały się do repo. Spróbuj je usunąć polecenium git rm a także zmodyfikuj plik gitignore tak aby nie dodawały się w przyszłości (więcej na temat gitignore znajdziesz tu https://pl.atlassian.com/git/tutorials/saving-changes/gitignore)

2018-12-30 19:29 UTC, jacekokrojek requested changes
Hej Kamilo, generalnie to wszyskie testy są OK, dałem tylko komentarz co do dodatkowych plików jakie się dodały do repo.

2019-01-01 22:08 UTC, kamamenszu commented on htmlReport.html
> +<!DOCTYPE html><html><head lang=en><meta charset=UTF-8><title></title><style>body{font-family:"open_sans",sans-serif}.suite{width:100%;overflow:auto}.suite .stats{margin:0;width:90%;padding:0}.suite
Hej, dokonałam poprawek, o jakie prosiłeś, zrobiłam nowego commita do tej samej branch.

2019-01-02 05:27 UTC, jacekokrojek commented on htmlReport.html
> +<!DOCTYPE html><html><head lang=en><meta charset=UTF-8><title></title><style>body{font-family:"open_sans",sans-serif}.suite{width:100%;overflow:auto}.suite .stats{margin:0;width:90%;padding:0}.suite
Hej Kamilo, 
wydaje mi się, że plik htmlReport.html ciągle jest w repozytorium

2019-01-02 13:19 UTC, jacekokrojek approved these changes

2019-01-02 13:20 UTC, merged