skonczone_2_zadanie
kamamenszu/jak-to-zrobic-w-js pull request #2
Opened 2019-01-01 23:41 UTC by kamamenszu

2019-01-02 05:30 UTC, jacekokrojek requested changes

2019-01-02 05:30 UTC, jacekokrojek commented on excercsises/2_page_object/contact.spec.js
> +		var headerGet = element(by.xpath('//fieldset/h3'));
Tutaj, chcielibyśmy mieć odwołanie do metod klasy contact, które zwracają interesujące nas elementy. Wprowadzilismy wzorzec Page Object aby z niego korzystać.

2019-01-02 12:38 UTC, kamamenszu commented on excercsises/2_page_object/contact.spec.js
> +		var headerGet = element(by.xpath('//fieldset/h3'));
Poprawione z Twoją pomocą.

2019-01-03 12:23 UTC, jacekokrojek approved these changes

2019-01-03 12:24 UTC, merged